=== DanielVerano/LenguajeMarcas/Unidad 1 - Introducción a los lenguajes de marcas. XML/U1_T2_DTD/discografica_ext.dtd
<!ELEMENT discografica (disco+)>
<!ELEMENT disco (titulo, interpretes, pistas)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT interpretes (interprete+)>
<!ELEMENT interprete (nombre, apellidos, rol?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT rol (#PCDATA)>
<!ELEMENT pistas (pista+)>
<!ELEMENT pista (nombre_cancion, duracion)>
<!ELEMENT nombre_cancion (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>

=== DanielVerano/LenguajeMarcas/Unidad 1 - Introducción a los lenguajes de marcas. XML/U1_T2_DTD/discografica_ext.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE discografica SYSTEM "discografica_ext.dtd">
<discografica>
  <disco>
    <titulo>Let It Be</titulo>
    <interpretes>
      <interprete>
        <nombre>John</nombre>
        <apellidos>Lennon</apellidos>
        <rol>Vocalista</rol>
      </interprete>
      <interprete>
        <nombre>Paul</nombre>
        <apellidos>McCartney</apellidos>
        <rol>Guitarrista</rol>
      </interprete>
      <interprete>
        <nombre>George</nombre>
        <apellidos>Harrison</apellidos>
      </interprete>
    </interpretes>
    <pistas>
      <pista>
        <nombre_cancion>Two of Us</nombre_cancion>
        <duracion>217</duracion>
      </pista>
      <pista>
        <nombre_cancion>Dig a Pony</nombre_cancion>
        <duracion>220</duracion>
      </pista>
      <pista>
        <nombre_cancion>Across the Universe</nombre_cancion>
        <duracion>220</duracion>
      </pista>
      <pista>
        <nombre_cancion>I Me Mine</nombre_cancion>
        <duracion>146</duracion>
      </pista>
      <pista>
        <nombre_cancion>Dig It</nombre_cancion>
        <duracion>50</duracion>
      </pista>
    </pistas>
  </disco>
</discografica>
